### ISSUE TITLE
[RFC] Incorrect Stick X/Y axis data decoding

### ISSUE THREAD

**Issue by CTCaer** [riking/joycon#16]
https://github.com/riking/joycon/blob/f02f96b1bfd41fcda5c9ff6eaef2e1d4e3f428fe/prog4/joycon/bluetooth.go#L434

Please refer to https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/bluetooth_hid_notes.md#standard-input-report---stick-data

**Comment by riking** [comment]
I think we can roll this into #15
