### ISSUE TITLE
Add remappable controls (ie control stick axis)

### ISSUE THREAD

**Issue by Noahkiq** [riking/joycon#18]
Recently found this project and got it setup to work in a few programs. While setting up my JoyCons in antimicro, I noticed that left=right, up=down, etc. This wasn't an issue in most programs I tried as they let me specify which direction should be positive/negative (ie retroarch, which has you setup control sticks by pressing up, down, left, and right). However, Steam only detects which axises are up/down and left/right, meaning all directions are inverted in Steam games, and I've found no option in Steam to fix this. Any help fixing this would be greatly appreciated 😄 
EDIT: OS is Ubuntu MATE 17.10 x64 in case it helps!

**Comment by Noahkiq** [comment]
Tried it with `jcmapper` instead after realizing I didn't build that, and it fixed the horizontal axis on both sticks, but not the vertical axis.

**Comment by riking** [comment]
Button remapping is on the to-do list. Take a look at the "invert" field in this file: https://github.com/riking/joycon/blob/master/prog4/output/keymap_common.go

**Comment by Noahkiq** [comment]
Swapping the `true`s and `false`s fixes the issue for me, thanks :)
