### ISSUE TITLE
Sticks don't have partial values; they're either 0, -1, or 1

### ISSUE THREAD

**Issue by TsundereBug** [riking/joycon#29]
This can be tested on [this site](https://html5gamepad.com)

**Comment by TsundereBug** [comment]
Nevermind, the joycon didn't show up in the tester or as an input device until the screenshot button was pressed. Interesting that it is supported by default.

**Comment by riking** [comment]
I have absolutely used that site during testing :)

**Comment by TsundereBug** [comment]
I was **wrong**. You pair the joycons like you do on the nintendo switch. Huh. Cool feature

**Comment by riking** [comment]
Which is another reason I should really work on giving this a GUI at some point...

**Comment by TsundereBug** [comment]
Take a look at nuklear :)
