### ISSUE TITLE
unable to compile: "cannot use func literal"

### ISSUE THREAD

**Issue by nickell-andrew** [riking/joycon#36]
`jcdriver/output_generic.go:11:9: cannot use func literal (type func(jcpc.JoyConType, int) (jcpc.Output, error)) as type jcpc.OutputFactory in return argument`

I get the error above when I attempt to run `go get ./...` or `go get ./jcdriver` from the prog4 directory. 

I'm running OSX 10.13

Full disclosure: I'm brand new to go and am mostly fiddling to see if I can effectively use joycon with my macbook pro

**Comment by nickell-andrew** [comment]
Update: I figured out that the function being returned didn't have the appropriate function signature. (should have been obvious but I'm still getting used to the syntax.

**Comment by riking** [comment]
Resolved by #37
