### ISSUE TITLE
Extra config needed to use it with Steam?

### ISSUE THREAD

**Issue by YPares** [riking/joycon#41]
Hi! I can connect the joycons but Steam big picture (and games) don't recognize them properly.
A and X are recognized as A and B, but left stick or buttons don't work in big picture.

Running Ubuntu 18.04

**Comment by YPares** [comment]
More generally, I guess my question is how to map joycon events to xinput events?

**Comment by YPares** [comment]
So I managed to have it mapped via Steam as a Xbox One controller, but some games don't recognize it, and oddly enough for a lot of games the left stick doesn't work

**Comment by riking** [comment]
Yeah a lot of games don't like the button config for some reason?

Duplicate of #39
