### ISSUE TITLE
Compilation keeps failing

### ISSUE THREAD

**Issue by 4techguns** [riking/joycon#54]
Every time I try to run go get -u github.com/riking/joycon/prog4/jcdriver it shows this:
![screenshot](https://user-images.githubusercontent.com/42378704/50699143-8f8f2900-1021-11e9-8b6f-063afa861769.png)

and then exits.
Do I need to remove the comment on the command for it to work?
edit: replaced text with picture

**Comment by parkerlreed** [comment]
You need to install that library. Depending on distro, it's probably `libudev-dev`

**Comment by 4techguns** [comment]
![screenshot_20190110_114626](https://user-images.githubusercontent.com/42378704/50977792-98727580-14cd-11e9-8554-d6eacb96ef2b.png)
Nope. Did not work.

**Comment by parkerlreed** [comment]
What distro are you on? I only gave debian based as an example.

**Comment by 4techguns** [comment]
Fedora

**Comment by 4techguns** [comment]
Nevermind, the lib was in systemd-devel.
