### ISSUE TITLE
Switching joy-cons from 1 to 2 button combo not working

### ISSUE THREAD

**Issue by drew-wallace** [riking/joycon#6]
I believe you said there was a button combo for switching back to 2 player mode but it got lost when GitHub went down for you. I just tried it after you said you added it back in and nothing happened.

**Comment by riking** [comment]
Oh! Switching after it's already been set up. No, there isn't a button combo for that. What do you think it should be? I can't think of anything besides an option in the UI to do that.

**Comment by drew-wallace** [comment]
What if you hold the home button + share button to combine them?

**Comment by riking** [comment]
Superseded by #24
